version: "3.3"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=etsy
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password